trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
# ✅ Install Terraform
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

# ✅ Terraform Init
- script: |
    echo "Initializing Terraform..."
    terraform init
  displayName: 'Terraform Init'
  workingDirectory: $(terraformWorkingDirectory)
  env:
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_TENANT_ID: $(ARM_TENANT_ID)

# ✅ Terraform Apply
- script: |
    echo "Applying Terraform..."
    terraform apply -auto-approve
  displayName: 'Terraform Apply'
  workingDirectory: $(terraformWorkingDirectory)


